// Bibliothèque de mots pour le jeu de l'Imposteur
// Chaque paire: { civil, imposter } — l'imposteur a un mot proche mais différent

export const CATEGORIES = {
  animaux: 'Animaux',
  nourriture: 'Nourriture',
  sport: 'Sport',
  lieux: 'Lieux',
  films: 'Films & Séries',
  metiers: 'Métiers',
  objets: 'Objets',
  marques: 'Marques & Tech',
}

export const WORD_PAIRS = {
  animaux: [
    { civil: 'Chien', imposter: 'Loup' },
    { civil: 'Chat', imposter: 'Tigre' },
    { civil: 'Lion', imposter: 'Panthère' },
    { civil: 'Éléphant', imposter: 'Rhinocéros' },
    { civil: 'Girafe', imposter: 'Zèbre' },
    { civil: 'Singe', imposter: 'Gorille' },
    { civil: 'Cheval', imposter: 'Âne' },
    { civil: 'Vache', imposter: 'Buffle' },
    { civil: 'Cochon', imposter: 'Sanglier' },
    { civil: 'Poule', imposter: 'Canard' },
    { civil: 'Aigle', imposter: 'Faucon' },
    { civil: 'Serpent', imposter: 'Lézard' },
    { civil: 'Crocodile', imposter: 'Alligator' },
    { civil: 'Requin', imposter: 'Dauphin' },
    { civil: 'Baleine', imposter: 'Orque' },
    { civil: 'Pingouin', imposter: 'Manchot' },
    { civil: 'Ours', imposter: 'Panda' },
    { civil: 'Renard', imposter: 'Coyote' },
    { civil: 'Lapin', imposter: 'Lièvre' },
    { civil: 'Souris', imposter: 'Rat' },
    { civil: 'Chèvre', imposter: 'Mouton' },
    { civil: 'Hibou', imposter: 'Chouette' },
    { civil: 'Grenouille', imposter: 'Crapaud' },
    { civil: 'Araignée', imposter: 'Scorpion' },
    { civil: 'Abeille', imposter: 'Guêpe' },
  ],
  nourriture: [
    { civil: 'Pizza', imposter: 'Tarte' },
    { civil: 'Burger', imposter: 'Sandwich' },
    { civil: 'Pâtes', imposter: 'Nouilles' },
    { civil: 'Riz', imposter: 'Couscous' },
    { civil: 'Frites', imposter: 'Chips' },
    { civil: 'Baguette', imposter: 'Pain de mie' },
    { civil: 'Croissant', imposter: 'Brioche' },
    { civil: 'Chocolat', imposter: 'Caramel' },
    { civil: 'Glace', imposter: 'Sorbet' },
    { civil: 'Yaourt', imposter: 'Fromage blanc' },
    { civil: 'Beurre', imposter: 'Margarine' },
    { civil: 'Pomme', imposter: 'Poire' },
    { civil: 'Banane', imposter: 'Plantain' },
    { civil: 'Orange', imposter: 'Mandarine' },
    { civil: 'Citron', imposter: 'Pamplemousse' },
    { civil: 'Mangue', imposter: 'Papaye' },
    { civil: 'Ananas', imposter: 'Noix de coco' },
    { civil: 'Tomate', imposter: 'Poivron' },
    { civil: 'Carotte', imposter: 'Patate douce' },
    { civil: 'Oignon', imposter: 'Échalote' },
    { civil: 'Poulet', imposter: 'Dinde' },
    { civil: 'Bœuf', imposter: 'Veau' },
    { civil: 'Crevette', imposter: 'Langoustine' },
    { civil: 'Café', imposter: 'Thé' },
    { civil: 'Ndolé', imposter: 'Eru' },
  ],
  sport: [
    { civil: 'Football', imposter: 'Rugby' },
    { civil: 'Basket', imposter: 'Handball' },
    { civil: 'Tennis', imposter: 'Badminton' },
    { civil: 'Boxe', imposter: 'Karaté' },
    { civil: 'Natation', imposter: 'Plongée' },
    { civil: 'Marathon', imposter: 'Sprint' },
    { civil: 'Cyclisme', imposter: 'Skateboard' },
    { civil: 'Ski', imposter: 'Snowboard' },
    { civil: 'Surf', imposter: 'Kitesurf' },
    { civil: 'Golf', imposter: 'Hockey' },
    { civil: 'Volley', imposter: 'Beach-volley' },
    { civil: 'Judo', imposter: 'Taekwondo' },
    { civil: 'Pétanque', imposter: 'Bowling' },
    { civil: 'Échecs', imposter: 'Dames' },
    { civil: 'Tir à l\'arc', imposter: 'Fléchettes' },
    { civil: 'Escalade', imposter: 'Alpinisme' },
    { civil: 'Yoga', imposter: 'Pilates' },
    { civil: 'Musculation', imposter: 'Crossfit' },
    { civil: 'Gymnastique', imposter: 'Parkour' },
    { civil: 'Patinage', imposter: 'Roller' },
    { civil: 'Voile', imposter: 'Aviron' },
    { civil: 'Équitation', imposter: 'Course hippique' },
    { civil: 'Formule 1', imposter: 'Karting' },
    { civil: 'Brawl Stars', imposter: 'Clash Royale' },
    { civil: 'FIFA', imposter: 'PES' },
  ],
  lieux: [
    { civil: 'Plage', imposter: 'Piscine' },
    { civil: 'Montagne', imposter: 'Colline' },
    { civil: 'Forêt', imposter: 'Jungle' },
    { civil: 'Désert', imposter: 'Savane' },
    { civil: 'Mer', imposter: 'Océan' },
    { civil: 'Rivière', imposter: 'Fleuve' },
    { civil: 'Lac', imposter: 'Étang' },
    { civil: 'Île', imposter: 'Presqu\'île' },
    { civil: 'Hôpital', imposter: 'Clinique' },
    { civil: 'École', imposter: 'Université' },
    { civil: 'Restaurant', imposter: 'Bar' },
    { civil: 'Cinéma', imposter: 'Théâtre' },
    { civil: 'Stade', imposter: 'Gymnase' },
    { civil: 'Église', imposter: 'Mosquée' },
    { civil: 'Marché', imposter: 'Supermarché' },
    { civil: 'Gare', imposter: 'Aéroport' },
    { civil: 'Hôtel', imposter: 'Auberge' },
    { civil: 'Maison', imposter: 'Appartement' },
    { civil: 'Château', imposter: 'Palais' },
    { civil: 'Cuisine', imposter: 'Salle à manger' },
    { civil: 'Chambre', imposter: 'Salon' },
    { civil: 'Garage', imposter: 'Atelier' },
    { civil: 'Yaoundé', imposter: 'Douala' },
    { civil: 'Paris', imposter: 'Londres' },
    { civil: 'New York', imposter: 'Los Angeles' },
  ],
  films: [
    { civil: 'Titanic', imposter: 'Avatar' },
    { civil: 'Avengers', imposter: 'Justice League' },
    { civil: 'Spider-Man', imposter: 'Batman' },
    { civil: 'Harry Potter', imposter: 'Seigneur des Anneaux' },
    { civil: 'Star Wars', imposter: 'Star Trek' },
    { civil: 'Game of Thrones', imposter: 'House of the Dragon' },
    { civil: 'Breaking Bad', imposter: 'Better Call Saul' },
    { civil: 'La Casa de Papel', imposter: 'Élite' },
    { civil: 'Squid Game', imposter: 'Alice in Borderland' },
    { civil: 'Friends', imposter: 'How I Met Your Mother' },
    { civil: 'The Office', imposter: 'Parks and Recreation' },
    { civil: 'Black Panther', imposter: 'Aquaman' },
    { civil: 'Fast and Furious', imposter: 'Bad Boys' },
    { civil: 'John Wick', imposter: 'Taken' },
    { civil: 'Mission Impossible', imposter: 'James Bond' },
    { civil: 'Rocky', imposter: 'Creed' },
    { civil: 'Le Roi Lion', imposter: 'Madagascar' },
    { civil: 'Toy Story', imposter: 'Cars' },
    { civil: 'Frozen', imposter: 'Raiponce' },
    { civil: 'Naruto', imposter: 'One Piece' },
    { civil: 'Dragon Ball', imposter: 'Bleach' },
    { civil: 'Walking Dead', imposter: 'Last of Us' },
    { civil: 'Lupin', imposter: 'Sherlock' },
    { civil: 'Stranger Things', imposter: 'Wednesday' },
    { civil: 'Inception', imposter: 'Interstellar' },
  ],
  metiers: [
    { civil: 'Médecin', imposter: 'Infirmier' },
    { civil: 'Avocat', imposter: 'Juge' },
    { civil: 'Professeur', imposter: 'Instituteur' },
    { civil: 'Policier', imposter: 'Gendarme' },
    { civil: 'Pompier', imposter: 'Secouriste' },
    { civil: 'Pilote', imposter: 'Steward' },
    { civil: 'Chauffeur', imposter: 'Taximan' },
    { civil: 'Boulanger', imposter: 'Pâtissier' },
    { civil: 'Cuisinier', imposter: 'Serveur' },
    { civil: 'Coiffeur', imposter: 'Barbier' },
    { civil: 'Mécanicien', imposter: 'Garagiste' },
    { civil: 'Plombier', imposter: 'Électricien' },
    { civil: 'Maçon', imposter: 'Charpentier' },
    { civil: 'Architecte', imposter: 'Ingénieur' },
    { civil: 'Développeur', imposter: 'Designer' },
    { civil: 'Comptable', imposter: 'Banquier' },
    { civil: 'Journaliste', imposter: 'Présentateur' },
    { civil: 'Photographe', imposter: 'Vidéaste' },
    { civil: 'Acteur', imposter: 'Réalisateur' },
    { civil: 'Chanteur', imposter: 'Rappeur' },
    { civil: 'Danseur', imposter: 'Chorégraphe' },
    { civil: 'Footballeur', imposter: 'Arbitre' },
    { civil: 'Soldat', imposter: 'Marine' },
    { civil: 'Agriculteur', imposter: 'Éleveur' },
    { civil: 'Pêcheur', imposter: 'Marin' },
  ],
  objets: [
    { civil: 'Téléphone', imposter: 'Tablette' },
    { civil: 'Ordinateur', imposter: 'Console' },
    { civil: 'Casque', imposter: 'Écouteurs' },
    { civil: 'Lunettes', imposter: 'Loupe' },
    { civil: 'Montre', imposter: 'Bracelet' },
    { civil: 'Sac à dos', imposter: 'Sacoche' },
    { civil: 'Parapluie', imposter: 'Imperméable' },
    { civil: 'Stylo', imposter: 'Crayon' },
    { civil: 'Livre', imposter: 'Magazine' },
    { civil: 'Lampe', imposter: 'Bougie' },
    { civil: 'Couteau', imposter: 'Fourchette' },
    { civil: 'Cuillère', imposter: 'Louche' },
    { civil: 'Assiette', imposter: 'Plateau' },
    { civil: 'Verre', imposter: 'Tasse' },
    { civil: 'Bouteille', imposter: 'Gourde' },
    { civil: 'Chaise', imposter: 'Tabouret' },
    { civil: 'Table', imposter: 'Bureau' },
    { civil: 'Lit', imposter: 'Canapé' },
    { civil: 'Couverture', imposter: 'Drap' },
    { civil: 'Oreiller', imposter: 'Coussin' },
    { civil: 'Miroir', imposter: 'Tableau' },
    { civil: 'Brosse à dents', imposter: 'Peigne' },
    { civil: 'Savon', imposter: 'Shampooing' },
    { civil: 'Clés', imposter: 'Cadenas' },
    { civil: 'Ventilateur', imposter: 'Climatiseur' },
  ],
  marques: [
    { civil: 'Apple', imposter: 'Samsung' },
    { civil: 'iPhone', imposter: 'Pixel' },
    { civil: 'Google', imposter: 'Bing' },
    { civil: 'YouTube', imposter: 'TikTok' },
    { civil: 'Instagram', imposter: 'Snapchat' },
    { civil: 'Facebook', imposter: 'Twitter' },
    { civil: 'WhatsApp', imposter: 'Telegram' },
    { civil: 'Netflix', imposter: 'Prime Video' },
    { civil: 'Spotify', imposter: 'Deezer' },
    { civil: 'Uber', imposter: 'Bolt' },
    { civil: 'Amazon', imposter: 'AliExpress' },
    { civil: 'Coca-Cola', imposter: 'Pepsi' },
    { civil: 'McDonald\'s', imposter: 'Burger King' },
    { civil: 'Nike', imposter: 'Adidas' },
    { civil: 'Mercedes', imposter: 'BMW' },
    { civil: 'Toyota', imposter: 'Honda' },
    { civil: 'Sony', imposter: 'LG' },
    { civil: 'Microsoft', imposter: 'Linux' },
    { civil: 'PlayStation', imposter: 'Xbox' },
    { civil: 'MTN', imposter: 'Orange' },
    { civil: 'Visa', imposter: 'Mastercard' },
    { civil: 'Mobile Money', imposter: 'Orange Money' },
    { civil: 'Bitcoin', imposter: 'Ethereum' },
    { civil: 'ChatGPT', imposter: 'Claude' },
    { civil: 'Fortnite', imposter: 'PUBG' },
  ],
}

// Tire une paire aléatoire dans une catégorie (ou toutes)
export function pickRandomPair(category = 'all') {
  let pool
  if (category === 'all' || !WORD_PAIRS[category]) {
    pool = Object.values(WORD_PAIRS).flat()
  } else {
    pool = WORD_PAIRS[category]
  }
  return pool[Math.floor(Math.random() * pool.length)]
}
